"""initial db

Revision ID: 55a8305272cc
Revises: 
Create Date: 2020-05-16 14:08:05.436493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a8305272cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64, collation='NOCASE'), nullable=False),
    sa.Column('manual_wins', sa.Integer(), nullable=False),
    sa.Column('manual_loses', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team1_player1_id', sa.Integer(), nullable=False),
    sa.Column('team1_player2_id', sa.Integer(), nullable=False),
    sa.Column('team2_player1_id', sa.Integer(), nullable=False),
    sa.Column('team2_player2_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('team1_score', sa.Integer(), nullable=False),
    sa.Column('team2_score', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team1_player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team1_player2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team2_player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team2_player2_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('is_for_team1', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_datas')
    op.drop_table('games')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
